"""FinOps & Business Intelligence — live smoke test of all 13 modules."""
import os, sys, uuid, json, tempfile
sys.path.insert(0, os.path.dirname(__file__))
from app.finops import *
ok = []

tmp = tempfile.mkdtemp()
print("=== FinOps & BI Platform Verification ===\n")

# 1. FinOps Engine
fe = FinOpsEngine(os.path.join(tmp, "finops"))
ce = CostEntry(id=str(uuid.uuid4()), org_id="org-1", workspace_id="ws-1", user_id="user-1", category=CostCategory.PROMPT_TOKENS, provider="openai", model="gpt-4", amount=0.05)
fe.track_cost(ce)
fe.track_cost(CostEntry(id=str(uuid.uuid4()), org_id="org-1", workspace_id="ws-1", user_id="user-1", category=CostCategory.GPU_USAGE, provider="aws", model="a100", amount=2.50))
summary = fe.get_cost_summary("org-1", "2025-01-01", "2026-12-31")
budget = Budget(id=str(uuid.uuid4()), org_id="org-1", name="monthly-ai", period=BudgetPeriod.MONTHLY, limit=1000.0)
fe.create_budget(budget)
forecast = fe.forecast_costs("org-1", BudgetPeriod.MONTHLY)
chargeback = fe.create_chargeback("org-1", BudgetPeriod.MONTHLY, ChargebackStrategy.USAGE_BASED)
showback = fe.generate_showback("org-1", BudgetPeriod.MONTHLY)
dash = fe.get_dashboard("org-1")
trends = fe.get_cost_trends("org-1", 30)
top = fe.get_top_spenders("org-1", 5)
roi = fe.calculate_roi("org-1", 10000, 25000, 90)
ok.append(f"total_cost={summary.total_cost:.2f}, budget_status={budget.current_spend:.2f}, forecast={forecast.predicted_cost:.2f}, chargebacks={len(chargeback.allocations)}, roi={roi['roi_percentage']:.1f}%")

# 2. AI Cost Tracking
act = AICostTracker(os.path.join(tmp, "ai_costs"))
usage = act.track_usage(TokenUsage(id=str(uuid.uuid4()), org_id="org-1", workspace_id="ws-1", user_id="user-1", model="gpt-4", provider="openai", token_type=TokenType.PROMPT, prompt_tokens=1000, completion_tokens=500, total_tokens=1500, cost=0.03))
entry = act.track_ai_cost(AICostEntry(id=str(uuid.uuid4()), org_id="org-1", workspace_id="ws-1", user_id="user-1", service=AIServiceType.LLM_CHAT, model="gpt-4", provider="openai", tier=ModelTier.STANDARD, unit=CostUnit.PER_TOKEN, usage_amount=1500, unit_price=0.02, total_cost=0.03))
rate = ProviderCostRate(id=str(uuid.uuid4()), provider="openai", model="gpt-4", tier=ModelTier.STANDARD, unit=CostUnit.PER_TOKEN, prompt_rate_per_million=10.0, completion_rate_per_million=30.0, embedding_rate_per_million=0.0, request_rate=0.0, hourly_rate=0.0)
act.register_provider_rate(rate)
calculated = act.calculate_cost("gpt-4", "openai", 1000, 500)
daily = act.get_daily_costs("org-1", "2025-01-01", "2026-12-31")
report = act.get_ai_cost_report("org-1", "2025-01-01", "2026-12-31")
top_models = act.get_top_costly_models("org-1", 5)
by_ws = act.get_usage_by_workspace("org-1")
by_svc = act.get_cost_by_service_type("org-1")
comparison = act.compare_provider_costs("gpt-4", ["openai", "anthropic"])
ok.append(f"tokens={usage.total_tokens}, calculated=${calculated['total_cost']:.4f}, models={len(top_models)}, providers={len(comparison)}")

# 3. Infrastructure Costs
icm = InfrastructureCostManager(os.path.join(tmp, "infra"))
res = icm.register_resource(InfraResource(id=str(uuid.uuid4()), name="gpu-cluster-1", resource_type=InfraResourceType.GPU, provider=InfraProvider.AWS, region="us-east-1", state=ResourceState.RUNNING, allocation=AllocationMethod.ON_DEMAND, specifications={"gpu_type": "A100", "memory_gb": 80}, hourly_cost=3.06, monthly_estimate=2200.0))
cost_entry = icm.track_cost(InfraCostEntry(id=str(uuid.uuid4()), org_id="org-1", workspace_id="ws-1", resource_id=res.id, resource_type=InfraResourceType.GPU, provider=InfraProvider.AWS, cost=3.06, usage_amount=1, usage_unit="hour", start_time="2025-06-01T00:00:00", end_time="2025-06-01T01:00:00", region="us-east-1", allocation=AllocationMethod.ON_DEMAND))
util = icm.record_utilization(ResourceUtilization(id=str(uuid.uuid4()), resource_id=res.id, resource_type=InfraResourceType.GPU, cpu_percent=45.0, memory_percent=60.0, gpu_percent=78.0, storage_percent=50.0, disk_iops=1200, network_in_bytes=1e9, network_out_bytes=2e9, requests_per_sec=150, avg_latency_ms=12, error_rate=0.01, timestamp="2025-06-01T01:00:00"))
summary_infra = icm.get_cost_summary("org-1", "2025-01-01", "2026-12-31")
under = icm.get_underutilized_resources("org-1", 0.2)
by_type = icm.get_cost_by_resource_type("org-1")
by_prov = icm.get_cost_by_provider("org-1")
monthly = icm.get_monthly_trend("org-1", 3)
ib = InfraBudget(id=str(uuid.uuid4()), org_id="org-1", name="gpu-budget", resource_type=InfraResourceType.GPU, provider=InfraProvider.AWS, period="monthly", limit=5000.0)
icm.create_infra_budget(ib)
ok.append(f"resources={len(icm.list_resources())}, infra_cost=${summary_infra.total_cost:.2f}, underutilized={len(under)}, by_type={len(by_type)}, by_prov={len(by_prov)}")

# 4. Organization Billing
ob = OrganizationBilling(os.path.join(tmp, "org_billing"))
profile = ob.create_billing_profile(OrganizationBillingProfile(id=str(uuid.uuid4()), org_id="org-1", name="Test Org", email="admin@test.com", address="123 Main St", tax_id="TAX-001", currency="USD", billing_cycle="monthly", status=BillingStatus.ACTIVE))
allocation = ob.set_workspace_allocation(WorkspaceBillingAllocation(id=str(uuid.uuid4()), org_id="org-1", workspace_id="ws-1", name="Engineering", allocation=AllocationType.PRORATED, percentage=50.0, fixed_amount=0.0, usage_factor=1.0, total_allocated=0.0, period_start="2025-01-01", period_end="2025-12-31"))
entity_costs = ob.allocate_costs_to_entities("org-1", BillingEntity.WORKSPACE, "2025-01-01", "2025-12-31")
invoice = ob.generate_invoice("org-1", "2025-01-01", "2025-12-31")
balance = ob.get_outstanding_balance("org-1")
revenue = ob.get_revenue_report("org-1", "2025-01-01", "2025-12-31")
ok.append(f"profile={profile.name}, entities={len(entity_costs)}, invoice=${invoice.total:.2f}, balance=${balance:.2f}")

# 5. Subscription Engine
sm = SubscriptionManager(os.path.join(tmp, "subscriptions"))
plan = sm.create_plan(Plan(id=str(uuid.uuid4()), name="Professional", type=PlanType.PROFESSIONAL, billing_cycle=BillingCycle.MONTHLY, base_price=99.0, price_per_seat=0.0, max_seats=10, max_repos=50, max_users=10, included_tokens=1000000, included_storage_gb=100, features=[FeatureCode.AI_REVIEW, FeatureCode.SECURITY_SCAN, FeatureCode.API_ACCESS], rate_limits={}, metadata={}))
sub = sm.create_subscription(Subscription(id=str(uuid.uuid4()), org_id="org-1", plan_id=plan.id, plan_type=PlanType.PROFESSIONAL, status=SubscriptionStatus.ACTIVE, billing_cycle=BillingCycle.MONTHLY, seats=5, start_date="2025-01-01", end_date="2025-12-31", trial_end_date="", auto_renew=True, payment_method=PaymentMethod.CREDIT_CARD, coupon_code="", discount_percent=0.0, current_bill=99.0, total_billed=99.0, metadata={}))
bill = sm.get_current_bill(sub.id)
inv_sub = sm.create_invoice(Invoice(id=str(uuid.uuid4()), org_id="org-1", subscription_id=sub.id, invoice_number="INV-001", amount=99.0, currency="USD", status="paid", period_start="2025-01-01", period_end="2025-01-31", issued_at="2025-01-01", paid_at="2025-01-01", items=[{"description": "Professional Plan", "amount": 99.0}], payment_method=PaymentMethod.CREDIT_CARD, metadata={}))
usage_rec = sm.record_usage(UsageRecord(id=str(uuid.uuid4()), org_id="org-1", subscription_id=sub.id, workspace_id="ws-1", metric_name="tokens", metric_value=50000, unit="tokens", timestamp="2025-06-01T00:00:00"))
credit = sm.add_credits("org-1", 100.0, "Promo credit")
balance_credits = sm.get_credit_balance("org-1")
validation = sm.validate_subscription("org-1")
sm.update_seats(sub.id, 8)
ok.append(f"plan={plan.name}, bill=${bill:.2f}, credits=${balance_credits:.2f}, valid={validation['valid']}, seats={sub.seats}")

# 6. Usage Analytics
ua = UsageAnalytics(os.path.join(tmp, "analytics"))
dp = ua.record_data_point(UsageDataPoint(id=str(uuid.uuid4()), org_id="org-1", workspace_id="ws-1", metric=UsageMetric.AI_REQUESTS, value=1500, unit="requests", timestamp="2025-06-01T00:00:00+00:00", source="api"))
ua.record_data_point(UsageDataPoint(id=str(uuid.uuid4()), org_id="org-1", workspace_id="ws-1", metric=UsageMetric.DAILY_ACTIVE_USERS, value=42, unit="users", timestamp="2025-06-01T00:00:00+00:00", source="system"))
snapshot = ua.get_current_snapshot("org-1")
trend = ua.analyze_trend("org-1", UsageMetric.AI_REQUESTS, AnalyticsPeriod.DAILY, 30)
dau = ua.get_daily_active_users("org-1", 7)
mau = ua.get_monthly_active_users("org-1", 3)
adoption = ua.get_adoption_rate("org-1")
growth = ua.get_growth_rate("org-1", UsageMetric.AI_REQUESTS, 30)
peak = ua.get_peak_usage_times("org-1", UsageMetric.AI_REQUESTS, 7)
usage_report = ua.generate_usage_report("org-1", "2025-01-01", "2026-12-31")
comparison = ua.compare_periods("org-1", UsageMetric.AI_REQUESTS, "2025-01-01", "2025-06-01", "2025-06-01", "2025-12-31")
ok.append(f"snapshot_metrics={len(snapshot.metrics)}, trend_dir={trend.direction.value}, dau={len(dau)}, mau={len(mau)}, growth={growth:.2f}")

# 7. Executive Dashboards
edm = ExecutiveDashboardManager(os.path.join(tmp, "dashboards"))
config = edm.create_dashboard_config(DashboardConfig(id=str(uuid.uuid4()), name="CEO Overview", type=DashboardType.CEO, org_id="org-1", owner="admin", period=DashboardPeriod.THIS_MONTH, sections=[], is_active=True))
ceo_dash = edm.generate_ceo_dashboard("org-1", DashboardPeriod.THIS_MONTH)
cto_dash = edm.generate_cto_dashboard("org-1", DashboardPeriod.THIS_MONTH)
eng_dash = edm.generate_engineering_dashboard("org-1", DashboardPeriod.THIS_MONTH)
fin_dash = edm.generate_finance_dashboard("org-1", DashboardPeriod.THIS_MONTH)
ops_dash = edm.generate_operations_dashboard("org-1", DashboardPeriod.THIS_MONTH)
sec_dash = edm.generate_security_dashboard("org-1", DashboardPeriod.THIS_MONTH)
prod_dash = edm.generate_product_dashboard("org-1", DashboardPeriod.THIS_MONTH)
cs_dash = edm.generate_customer_success_dashboard("org-1", DashboardPeriod.THIS_MONTH)
kpi = edm.get_kpi_summary("org-1", DashboardType.CEO, DashboardPeriod.THIS_MONTH)
ok.append(f"dashboards={len(edm.list_dashboards('org-1'))}, ceo_metrics={len(ceo_dash.summary_metrics)}, kpi_revenue=${kpi.total_revenue:.2f}")

# 8. Forecasting
fe_forecast = ForecastingEngine(os.path.join(tmp, "forecasts"))
fi = fe_forecast.create_forecast_input(ForecastInput(id=str(uuid.uuid4()), org_id="org-1", metric=ForecastMetric.MONTHLY_REVENUE, historical_data=[10000, 12000, 11000, 13000, 14000, 13500], periods_lookback=6, periods_forecast=3, model=ForecastModel.LINEAR_REGRESSION, confidence=ConfidenceLevel.HIGH))
result = fe_forecast.run_forecast(fi.id)
rev_forecast = fe_forecast.forecast_revenue("org-1", 12, [10000, 11000, 12000, 11500, 13000, 14000, 13500, 15000, 16000, 15500, 17000, 18000])
cap_forecast = fe_forecast.forecast_capacity("org-1", 6)
model_compare = fe_forecast.compare_models(fi.id, [ForecastModel.LINEAR_REGRESSION, ForecastModel.MOVING_AVERAGE, ForecastModel.EXPONENTIAL_SMOOTHING])
scenario = fe_forecast.run_scenario_analysis("org-1", ForecastMetric.MONTHLY_REVENUE, {"optimistic": {"growth_multiplier": 1.2}, "pessimistic": {"growth_multiplier": 0.8}})
accuracy = fe_forecast.calculate_accuracy([100, 110, 120], [102, 108, 122])
trend_line = fe_forecast.generate_trend_line([100, 110, 120, 115, 130, 125, 140, 135, 150, 145, 160, 155], 12)
seasonality = fe_forecast.detect_seasonality([10, 12, 11, 13, 14, 13, 15, 16, 15, 17, 18, 17, 10, 12, 11, 13, 14, 13, 15, 16, 15, 17, 18, 17], 12)
ok.append(f"forecast_input={len(result.predictions)}, rev_arr=${rev_forecast.projected_arr:.2f}, gpu_proj={cap_forecast.projected_gpu_usage:.0f}, models_compared={len(model_compare)}, accuracy_mape={accuracy['mape']:.2f}")

# 9. ROI Engine
roi_eng = ROIEngine(os.path.join(tmp, "roi"))
roi_metric = roi_eng.create_roi_metric(ROIMetric(id=str(uuid.uuid4()), org_id="org-1", workspace_id="ws-1", category=ROICategory.DEVELOPER_TIME_SAVED, name="PR Review Time", description="Hours saved on PR reviews", unit="hours", target_value=200, current_value=150, baseline_value=300, measurement_interval="monthly", status=ROIStatus.ON_TARGET))
savings = roi_eng.record_time_savings(TimeSavingsMetric(id=str(uuid.uuid4()), org_id="org-1", category=ROICategory.DEVELOPER_TIME_SAVED, task_name="Code Review", manual_hours=100, automated_hours=20, hours_saved=80, hourly_rate=75.0, total_savings=6000.0, developers_affected=10, frequency_per_week=20))
quality = roi_eng.record_quality_metric(QualityMetric(id=str(uuid.uuid4()), org_id="org-1", category=ROICategory.CODE_QUALITY, metric_name="Bug Rate", before_value=15, after_value=5, improvement_percent=66.7, impact_area="Stability", measurement_method="manual", measured_at="2025-06-01"))
time_saved = roi_eng.calculate_developer_time_saved("org-1", "2025-01-01", "2025-12-31")
ai_prod = roi_eng.calculate_ai_productivity("org-1", "2025-01-01", "2025-12-31")
quality_improvement = roi_eng.calculate_code_quality_improvement("org-1", "2025-01-01", "2025-12-31")
infra_opt = roi_eng.calculate_infrastructure_optimization("org-1", "2025-01-01", "2025-12-31")
total_roi = roi_eng.calculate_total_roi("org-1", "2025-01-01", "2025-12-31", 50000)
velocity = roi_eng.estimate_engineering_velocity("org-1")
prod_report = roi_eng.generate_productivity_report("org-1", "2025-01-01", "2025-12-31")
roi_trend = roi_eng.get_roi_trend("org-1", 3)
roi_by_cat = roi_eng.get_roi_by_category("org-1")
ok.append(f"roi_metrics={len(roi_eng.list_roi_metrics('org-1'))}, total_roi=${total_roi.total_benefits:.2f}, velocity_score={velocity.get('velocity_score', 0):.2f}")

# 10. Reporting
rg = ReportGenerator(os.path.join(tmp, "reports"))
rdef = rg.create_report_definition(ReportDefinition(id=str(uuid.uuid4()), org_id="org-1", name="Monthly Executive", description="Monthly report", type=ReportType.MONTHLY, sections=[ReportSection.FINANCIAL_SUMMARY, ReportSection.USAGE_ANALYTICS, ReportSection.FORECAST], format=ReportFormat.JSON, filters={}, recipients=["admin@test.com"]))
weekly = rg.generate_weekly_report("org-1")
monthly = rg.generate_monthly_report("org-1")
quarterly = rg.generate_quarterly_report("org-1")
annual = rg.generate_annual_report("org-1")
exec_summary = rg.generate_executive_summary("org-1", ReportType.MONTHLY, "2025-01-01", "2025-06-01")
dept_report = rg.generate_department_report("org-1", "Engineering", "2025-01-01", "2025-06-01")
sched = rg.schedule_report(ReportSchedule(id=str(uuid.uuid4()), report_def_id=rdef.id, org_id="org-1", frequency=ScheduleFrequency.WEEKLY, next_run="2025-07-01T00:00:00", last_run="", recipients=["admin@test.com"], format=ReportFormat.JSON, is_active=True))
run_scheduled = rg.run_scheduled_reports()
ok.append(f"defs={len(rg.list_report_definitions('org-1'))}, weekly_sections={len(weekly.sections_data)}, exec_highlights={len(exec_summary.key_highlights)}, scheduled={len(run_scheduled)}")

# 11. Alerts
am = AlertManager(os.path.join(tmp, "alerts"))
rule = am.create_rule(AlertRule(id=str(uuid.uuid4()), org_id="org-1", name="Budget Alert", category=AlertCategory.BUDGET_EXCEEDED, severity=AlertSeverity.HIGH, metric_name="monthly_spend", condition=">", threshold=1000.0, duration_minutes=60, cooldown_minutes=1440, channels=[NotificationChannel.EMAIL, NotificationChannel.SLACK], enabled=True))
events = am.evaluate_rules("org-1", {"monthly_spend": 1200.0})
if events:
    am.acknowledge_alert(events[0].id, "admin-1")
    am.resolve_alert(events[0].id, "admin-1")
active = am.get_active_alerts("org-1")
history = am.get_alert_history("org-1", 30)
stats = am.get_alert_stats("org-1")
policy = am.create_escalation_policy(AlertEscalationPolicy(id=str(uuid.uuid4()), org_id="org-1", name="critical-escalation", category=AlertCategory.BUDGET_EXCEEDED, levels=["l1", "l2", "l3"], wait_minutes=[15, 30, 60], notify=["team-lead", "manager", "director"]))
ok.append(f"rules={len(am.list_rules('org-1'))}, triggered={len(events)}, active={len(active)}, stats_rules={stats.get('total_rules', 0)}")

# 12. Data Warehouse
dw = DataWarehouse(os.path.join(tmp, "warehouse"))
config = dw.configure(WarehouseConfig(id=str(uuid.uuid4()), org_id="org-1", name="cost-warehouse", data_entity=DataEntity.COST_ENTRY, aggregation=AggregationLevel.DAILY, retention_days=365, retention_policy=RetentionPolicy.ARCHIVE_AFTER, compress_data=True, enabled=True))
dw.ingest_record(DataEntity.COST_ENTRY, {"id": "c1", "org_id": "org-1", "cost": 50.0, "date": "2025-06-01"})
agg = dw.run_aggregation("org-1", DataEntity.COST_ENTRY, AggregationLevel.DAILY)
trend_seg = dw.analyze_trends("org-1", "cost", AggregationLevel.DAILY, 3)
archive = dw.archive_data("org-1", DataEntity.COST_ENTRY, 365)
stats_dw = dw.get_warehouse_stats("org-1")
ok.append(f"config={config.name}, agg_total=${agg.total_value:.2f}, archived_records={archive.record_count}")

# 13. Exports
em = ExportManager(os.path.join(tmp, "exports"))
ereq = em.create_export_request(ExportRequest(id=str(uuid.uuid4()), org_id="org-1", user_id="user-1", name="test-export", format=ExportFormat.JSON, scope=ExportScope.FULL, data_type="costs", filters={}, columns=["id", "cost"], compression=ExportCompression.NONE))
data = [{"id": "1", "cost": 10.0}, {"id": "2", "cost": 20.0}]
csv_result = em.export_to_csv(ereq.id, data)
json_result = em.export_to_json(ereq.id, data)
html_result = em.export_to_html(ereq.id, data, "Cost Report")
md_result = em.export_to_markdown(ereq.id, data, "Cost Report")
auto_result = em.export_data(ereq.id, data)
tpl = em.create_export_template(ExportTemplate(id=str(uuid.uuid4()), org_id="org-1", name="default-csv", format=ExportFormat.CSV, data_type="costs", columns=["id", "cost"], filters={}, options={}))
ok.append(f"csv={csv_result.row_count} rows, auto={auto_result.format.value}, templates={len(em.list_templates('org-1'))}")

print(f"\nAll {len(ok)}/13 modules verified successfully.")
for i, msg in enumerate(ok, 1):
    print(f"  {i:2d}. {msg}")
print("\nDone.")
