export interface DocEntry {
  id: string;
  title: string;
  category: string;
  href: string;
  keywords: string[];
  summary: string;
}

export const DOCS_INDEX: DocEntry[] = [
  // GETTING STARTED
  {
    id: "overview",
    title: "Overview",
    category: "Getting Started",
    href: "/docs#overview",
    keywords: ["overview", "introduction", "novaforge"],
    summary: "NovaForge AI enterprise platform — React + FastAPI, tenant-scoped, server-authoritative.",
  },
  {
    id: "quick-start",
    title: "Quick Start",
    category: "Getting Started",
    href: "/docs#quick-start",
    keywords: ["quick start", "getting started", "setup"],
    summary: "Run with Docker or local dev: backend .venv and frontend npm run dev at localhost:3000.",
  },
  {
    id: "navigation",
    title: "Navigation",
    category: "Getting Started",
    href: "/docs#navigation",
    keywords: ["navigation", "command palette", "sidebar"],
    summary: "Use SideNav groups and Command Palette Go to Documentation → /docs, Go to Developer → /developer.",
  },
  {
    id: "authentication",
    title: "Authentication",
    category: "Getting Started",
    href: "/docs#authentication",
    keywords: ["auth", "login", "api key", "bearer", "mfa"],
    summary: "Auth via POST /auth/login, X-API-Key nf_ prefix sha256, Bearer JWT, MFA totp/backup_code.",
  },
  // PLATFORM
  {
    id: "dashboard",
    title: "Dashboard",
    category: "Platform",
    href: "/dashboard",
    keywords: ["dashboard", "account", "usage"],
    summary: "Account, usage and search overview — authenticated, tenant-scoped.",
  },
  {
    id: "ai",
    title: "AI",
    category: "Platform",
    href: "/ai",
    keywords: ["ai", "workspace", "conversations"],
    summary: "AI workspace and conversations — POST /ai-dev/explain, /ai-dev/patch.",
  },
  {
    id: "code",
    title: "Code",
    category: "Platform",
    href: "/code",
    keywords: ["code", "intelligence", "graph"],
    summary: "Code intelligence workspace — POST /code/analyze, /code-intelligence/{repo}/search, graph traverse.",
  },
  {
    id: "knowledge",
    title: "Knowledge",
    category: "Platform",
    href: "/knowledge",
    keywords: ["knowledge", "rag", "search"],
    summary: "Search the knowledge base and universal search across the platform.",
  },
  {
    id: "data",
    title: "Data Platform",
    category: "Platform",
    href: "/data",
    keywords: ["data", "datasets", "pipelines"],
    summary: "Datasets, pipelines and catalog — lakehouse /api/v1/lakehouse/*.",
  },
  {
    id: "workflows",
    title: "Workflows",
    category: "Platform",
    href: "/workflows",
    keywords: ["workflows", "automation"],
    summary: "Workflow automation — tenant-scoped templates and runs.",
  },
  {
    id: "agents",
    title: "Agents",
    category: "Platform",
    href: "/agents",
    keywords: ["agents", "ai agent", "plans"],
    summary: "AI agent platform — POST /ai-dev/agents, /agents/{id}/execute, plans/checkpoints.",
  },
  {
    id: "analytics",
    title: "Analytics",
    category: "Platform",
    href: "/analytics",
    keywords: ["analytics", "executive"],
    summary: "Executive analytics across the platform — spend, budgets, posture.",
  },
  // OPERATIONS
  {
    id: "observability",
    title: "Observability",
    category: "Operations",
    href: "/observability",
    keywords: ["observability", "status", "health"],
    summary: "Operational status and health — GET /health, /metrics.",
  },
  {
    id: "security",
    title: "Security",
    category: "Operations",
    href: "/security",
    keywords: ["security", "posture", "findings"],
    summary: "Posture, findings and zero trust — POST /security/plugin/mcp/validate (validate-only).",
  },
  {
    id: "governance",
    title: "Governance",
    category: "Operations",
    href: "/governance",
    keywords: ["governance", "policies", "rules"],
    summary: "Policies, rules and posture — governance controls.",
  },
  {
    id: "integrations",
    title: "Integrations",
    category: "Operations",
    href: "/integrations",
    keywords: ["integrations", "webhooks", "connections"],
    summary: "Connected systems — GET /integrations, /integrations/connections/all, /integrations/webhooks/all.",
  },
  {
    id: "finops",
    title: "FinOps",
    category: "Operations",
    href: "/finops",
    keywords: ["finops", "spend", "budgets"],
    summary: "Spend and budgets — FinOps workspace.",
  },
  {
    id: "notifications",
    title: "Notifications",
    category: "Operations",
    href: "/notifications",
    keywords: ["notifications", "preferences"],
    summary: "Notifications, unread activity and preferences — /notifications.",
  },
  // DEVELOPER
  {
    id: "api",
    title: "API",
    category: "Developer",
    href: "/docs#api",
    keywords: ["api", "openapi", "swagger"],
    summary: "Backend-verified API — Swagger UI /docs, OpenAPI JSON /openapi.json, Discovery /.well-known/novaforge.json.",
  },
  {
    id: "sdk",
    title: "SDK",
    category: "Developer",
    href: "/docs#sdk",
    keywords: ["sdk", "python", "integrations"],
    summary: "Python SDK backend/sdk/integrations.py — IntegrationMixin 21 methods, token via POST /auth/token-exchange.",
  },
  {
    id: "cli",
    title: "CLI",
    category: "Developer",
    href: "/docs#cli",
    keywords: ["cli", "nova", "orchestrator"],
    summary: "NovaForge CLI — nova integrations list, cli/novaforge_cli.py 30-volume orchestrator, backend/cli/main.py.",
  },
  {
    id: "mcp",
    title: "MCP",
    category: "Developer",
    href: "/docs#mcp",
    keywords: ["mcp", "validate", "transport"],
    summary: "MCP validation only — POST /security/plugin/mcp/validate, no runtime transport exposed (NOT EXPOSED BY API).",
  },
  {
    id: "code-intelligence",
    title: "Code Intelligence",
    category: "Developer",
    href: "/code",
    keywords: ["code intelligence", "graph", "symbols"],
    summary: "Repository indexing, code search, RAG context, impact analysis via /code-intelligence/{repo}/*.",
  },
  {
    id: "ai-developer",
    title: "AI Developer Platform",
    category: "Developer",
    href: "/ai",
    keywords: ["ai developer", "explain", "patch"],
    summary: "AI code explanation, change summary, test generation via POST /ai-dev/explain, /ai-dev/patch.",
  },
  // ADMINISTRATION
  {
    id: "organization",
    title: "Organization",
    category: "Administration",
    href: "/settings/organization",
    keywords: ["organization", "administration"],
    summary: "Workspace administration — organization settings.",
  },
  {
    id: "members",
    title: "Members",
    category: "Administration",
    href: "/settings/members",
    keywords: ["members", "users"],
    summary: "Members and user management.",
  },
  {
    id: "roles",
    title: "Roles",
    category: "Administration",
    href: "/settings/roles",
    keywords: ["roles", "permissions"],
    summary: "Roles and permission assignments — settings:admin, organization:read, etc.",
  },
  {
    id: "workspaces",
    title: "Workspaces",
    category: "Administration",
    href: "/settings/workspaces",
    keywords: ["workspaces", "tenant"],
    summary: "Workspace isolation — tenant:switched and workspace:switched events.",
  },
  {
    id: "identity",
    title: "Identity & Access",
    category: "Administration",
    href: "/settings/identity",
    keywords: ["identity", "access", "authentication"],
    summary: "Enterprise identity, authentication and access visibility — /settings/identity.",
  },
  {
    id: "preferences",
    title: "Preferences",
    category: "Administration",
    href: "/settings/preferences",
    keywords: ["preferences", "personalization"],
    summary: "Personalization overview — /settings/preferences.",
  },
  // HELP
  {
    id: "faq",
    title: "FAQ",
    category: "Help",
    href: "/docs#faq",
    keywords: ["faq", "questions"],
    summary: "Frequently asked questions about workspace, API keys, notifications, and integrations.",
  },
  {
    id: "troubleshooting",
    title: "Troubleshooting",
    category: "Help",
    href: "/docs#troubleshooting",
    keywords: ["troubleshooting", "errors", "session expired"],
    summary: "SESSION EXPIRED, ACCESS DENIED, RESOURCE NOT FOUND, CONFLICT, INVALID REQUEST, SERVICE UNAVAILABLE.",
  },
  {
    id: "support",
    title: "Support",
    category: "Help",
    href: "/docs#support",
    keywords: ["support", "help", "ask ai"],
    summary: "Support and help — Ask AI → /ai, Developer Platform → /developer.",
  },
];
